/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJE2_H_RPCGEN
#define _EJE2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXIMO 20

struct persona {
	char *nombre;
	char *apellido;
	int edad;
	char *provincia;
};
typedef struct persona persona;

struct vector_personas {
	struct {
		u_int vector_len;
		persona *vector_val;
	} vector;
};
typedef struct vector_personas vector_personas;

#define PROGRAMA 0x30000005
#define BUSCAR 1

#if defined(__STDC__) || defined(__cplusplus)
#define buscarApellido 1
extern  persona * buscarapellido_1(vector_personas *, CLIENT *);
extern  persona * buscarapellido_1_svc(vector_personas *, struct svc_req *);
#define menorEdad 2
extern  persona * menoredad_1(vector_personas *, CLIENT *);
extern  persona * menoredad_1_svc(vector_personas *, struct svc_req *);
extern int programa_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define buscarApellido 1
extern  persona * buscarapellido_1();
extern  persona * buscarapellido_1_svc();
#define menorEdad 2
extern  persona * menoredad_1();
extern  persona * menoredad_1_svc();
extern int programa_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_persona (XDR *, persona*);
extern  bool_t xdr_vector_personas (XDR *, vector_personas*);

#else /* K&R C */
extern bool_t xdr_persona ();
extern bool_t xdr_vector_personas ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJE2_H_RPCGEN */
