/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "eje2.h"


void
programa_1(char *host)
{
	CLIENT *clnt;
	persona  *result_1;
	vector_personas  buscarapellido_1_arg;
	persona  *result_2;
	vector_personas  menoredad_1_arg;
	char aux[MAXIMO];

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA, BUSCAR, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	system("clear");
	printf("Escriba el apellido a buscar\n");
	scanf("%s", aux);
	buscarapellido_1_arg.vector.vector_len=MAXIMO;
	buscarapellido_1_arg.vector.vector_val= malloc(sizeof(vector_personas)*MAXIMO);
	strcpy(buscarapellido_1_arg.vector.vector_val[0].apellido, aux);
	result_1 = buscarapellido_1(&buscarapellido_1_arg, clnt);
	if (result_1 == (persona *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		fprintf(stderr, "%s %s %d %s \n", result_1->nombre, result_1->apellido, result_1->edad, result_1->provincia);
	}
	result_2 = menoredad_1(&menoredad_1_arg, clnt);
	if (result_2 == (persona *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	programa_1 (host);
exit (0);
}

