/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HOLAMUNDO_H_RPCGEN
#define _HOLAMUNDO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define HOLAMUNDO 0x30000002
#define HOLAMUNDO_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define hola 1
extern  char ** hola_1(char **, CLIENT *);
extern  char ** hola_1_svc(char **, struct svc_req *);
extern int holamundo_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define hola 1
extern  char ** hola_1();
extern  char ** hola_1_svc();
extern int holamundo_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HOLAMUNDO_H_RPCGEN */
