/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "eje2.h"

persona *
bucasapell_1_svc(array_personas *argp, struct svc_req *rqstp)
{
	static persona  result;
	persona aux;
	FILE *f;
	f=fopen("personas.txt", "r");
	while(fscanf(f, "%s %s, %d, %s", aux.nombre, aux.apellido, aux.edad, aux.provincia)== 4)
	{
		if(strcmp(argp->Registros.Registros_val[0].apellido, aux.apellido)==0)
		{
			result=aux;
		}
	}

	return &result;
}

persona *
menoredad_1_svc(array_personas *argp, struct svc_req *rqstp)
{
	static persona  result;

	/*
	 * insert server code here
	 */

	return &result;
}
