/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJE2_H_RPCGEN
#define _EJE2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXIMO 20

struct persona {
	char *nombre;
	char *apellido;
	int edad;
	char *provincia;
};
typedef struct persona persona;

struct array_personas {
	struct {
		u_int Registros_len;
		persona *Registros_val;
	} Registros;
	int cant_devuelte;
};
typedef struct array_personas array_personas;

struct parametros_b {
	char *provincia;
	int edad;
};
typedef struct parametros_b parametros_b;

#define PROGRAMA 0x30000019
#define BUSCAR 1

#if defined(__STDC__) || defined(__cplusplus)
#define bucasApell 1
extern  persona * bucasapell_1(array_personas *, CLIENT *);
extern  persona * bucasapell_1_svc(array_personas *, struct svc_req *);
#define menorEdad 2
extern  persona * menoredad_1(array_personas *, CLIENT *);
extern  persona * menoredad_1_svc(array_personas *, struct svc_req *);
extern int programa_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define bucasApell 1
extern  persona * bucasapell_1();
extern  persona * bucasapell_1_svc();
#define menorEdad 2
extern  persona * menoredad_1();
extern  persona * menoredad_1_svc();
extern int programa_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_persona (XDR *, persona*);
extern  bool_t xdr_array_personas (XDR *, array_personas*);
extern  bool_t xdr_parametros_b (XDR *, parametros_b*);

#else /* K&R C */
extern bool_t xdr_persona ();
extern bool_t xdr_array_personas ();
extern bool_t xdr_parametros_b ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJE2_H_RPCGEN */
