/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "eje2.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

persona *
bucasapell_1(array_personas *argp, CLIENT *clnt)
{
	static persona clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, bucasApell,
		(xdrproc_t) xdr_array_personas, (caddr_t) argp,
		(xdrproc_t) xdr_persona, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

persona *
menoredad_1(array_personas *argp, CLIENT *clnt)
{
	static persona clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, menorEdad,
		(xdrproc_t) xdr_array_personas, (caddr_t) argp,
		(xdrproc_t) xdr_persona, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
