/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "eje2.h"


void
programa_1(char *host, char *apellido)
{
	CLIENT *clnt;
	persona  *result_1;
	array_personas  bucasapell_1_arg;
	persona  *result_2;
	array_personas  menoredad_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA, BUSCAR, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	//Inicializamos el vector de personas
	bucasapell_1_arg.Registros.Registros_len = MAXIMO;
	bucasapell_1_arg.Registros.Registros_val=malloc(sizeof(int)*MAXIMO);

	//Rellenamos la primera posición del vector con el apellido a buscar
	strcpy(bucasapell_1_arg.Registros.Registros_val[0].apellido, apellido);
	
	result_1 = bucasapell_1(&bucasapell_1_arg, clnt);
	if (result_1 == (persona *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("%s %s, %d, %s \n", result_1->nombre, result_1->apellido, result_1->edad, result_1->provincia);
	}


	result_2 = menoredad_1(&menoredad_1_arg, clnt);
	if (result_2 == (persona *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *apellido;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	apellido = argv[2];
	programa_1 (host, apellido);
exit (0);
}
