/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *media_1_svc(vector_cal *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;
	int aux=0;
	system("clear");
	fprintf(stderr, "---Desde el servidor---\n");

	for(i=0;i<argp->vector.vector_len;i++)
	{
		fprintf(stderr, "%d ", argp->vector.vector_val[i]);
		aux+=argp->vector.vector_val[i];
	}
	result=aux/argp->vector.vector_len;

	return &result;
}

int *maximo_1_svc(vector_cal *argp, struct svc_req *rqstp)
{
	static int  result;

	int i;
	int aux=0;

	puts("");
	for(i=0;i<argp->vector.vector_len;i++)
	{
		fprintf(stderr, "%d ", argp->vector.vector_val[i]);
		if(aux<argp->vector.vector_val[i])
		{
			aux=argp->vector.vector_val[i];
		}
	}
	result=aux;

	return &result;
}

int *factorial_1_svc(vector_cal *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;
	int aux=1;
	for(i=1; i<=argp->vector.vector_val[0];i++)
	{
		aux*=i;
	}
	result=aux;

	return &result;
}
